<?php

/**
 * @file
 * Contains user_insert.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user\UserInterface;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function user_insert_user_insert($account) {
  /** @var QueueFactory $queue_factory */
  $queue_factory = \Drupal::service('queue');
  /** @var QueueInterface $queue */
  $queue = $queue_factory->get('user_insert');
  $queue->createItem($account->id());
}

/**
 * Implements hook_mail().
 */
function user_insert_mail($key, &$message, $params) {
 $options = array(
   'langcode' => $message['langcode'],
 );
 switch ($key) {
   case 'create_user':
     $message['from'] = \Drupal::config('system.site')->get('mail');
     $message['subject'] = t('User created: @title', array('@title' => $params['user_title']), $options);
     $message['body'][] = $params['message'];
     break;
 }
}
